# Generated by Django 6.0.4 on 2026-04-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=160)),
                ('tin_number', models.CharField(max_length=40, unique=True)),
                ('trade_name', models.CharField(blank=True, default='', max_length=180)),
                ('location', models.CharField(max_length=180)),
                ('permit_number', models.CharField(max_length=80)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='safebooks.bookkeeperaccount')),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['client_name', 'id'],
                'indexes': [models.Index(fields=['bookkeeper'], name='clients_bookkee_0cacf6_idx'), models.Index(fields=['client_name'], name='clients_client__3f3dca_idx'), models.Index(fields=['risk_level'], name='clients_risk_le_e45799_idx')],
            },
        ),
    ]
