# Generated by Django 6.0.4 on 2026-04-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='safebooks.client')),
            ],
            options={
                'db_table': 'periods',
                'ordering': ['-year', '-month', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='safebooks.bookkeeperaccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='safebooks.client')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='safebooks.period')),
            ],
            options={
                'db_table': 'financial_records',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecordLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='safebooks.financialrecord')),
            ],
            options={
                'db_table': 'financial_record_lines',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['record'], name='financial_r_record__8e827d_idx'), models.Index(fields=['type_code'], name='financial_r_type_co_b22a99_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['client'], name='periods_client__aa7687_idx'),
        ),
        migrations.AddIndex(
            model_name='period',
            index=models.Index(fields=['year', 'month'], name='periods_year_7d9471_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='period',
            unique_together={('client', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['bookkeeper'], name='financial_r_bookkee_cbf74e_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['client'], name='financial_r_client__564f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['period'], name='financial_r_period__ade8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['entry_date'], name='financial_r_entry_d_db88f5_idx'),
        ),
    ]
