# Generated by Django 6.0.4 on 2026-05-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0005_client_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='monthly', max_length=16),
        ),
    ]
