# Generated by Django 6.0.4 on 2026-05-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0006_financialrecord_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='permit_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
