# Generated by Django 6.0.4 on 2026-05-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0007_alter_client_permit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecordline',
            name='calc_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialrecordline',
            name='calc_operation',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('subtract', 'Subtract'), ('multiply', 'Multiply'), ('divide', 'Divide'), ('percent', 'Percent')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='financialrecordline',
            name='calc_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='financialrecordline',
            name='calc_result',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='financialrecordline',
            name='calc_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calc_sources', to='safebooks.financialrecordline'),
        ),
    ]
