# Generated by Django 6.0.4 on 2026-05-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0008_financialrecordline_calc_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecordline',
            name='calc_original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
