# Generated by Django 6.0.4 on 2026-05-17 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0005_bookkeeper_email_verification'),
        ('safebooks', '0010_merge_20260513_1057'),
    ]

    operations = [
    ]
