# Generated by Django 6.0.4 on 2026-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0019_remove_financialrecordline_calc_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_risk_le_e45799_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='remarks',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('separated', 'Separated'), ('terminated', 'Terminated')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacedefaults',
            name='default_report_type',
            field=models.CharField(choices=[('financial_summary', 'Financial Summary'), ('compliance_snapshot', 'Compliance Snapshot'), ('client_remarks_overview', 'Client Remarks Overview')], default='financial_summary', max_length=32),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['remarks'], name='clients_remarks_84debd_idx'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='risk_level',
        ),
    ]
