# Generated by Django 6.0.4 on 2026-05-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0020_remove_client_clients_risk_le_e45799_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='remarks',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('separated', 'Separated'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
