# Generated by Django 6.0.4 on 2026-05-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0021_alter_client_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
