# Generated by Django 6.0.4 on 2026-05-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0022_financialrecord_deadline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='forecast_growth_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
