# Generated by Django 6.0.4 on 2026-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0025_enable_client_details_lock_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeperaccount',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
