# Generated by SafeBooks on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safebooks", "0026_bookkeeperaccount_google_sub"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(db_index=True, max_length=80)),
                ("target_model", models.CharField(max_length=80)),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="safebooks.adminaccount",
                    ),
                ),
            ],
            options={
                "db_table": "admin_audit_logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(fields=["action_type", "-created_at"], name="admin_audit_action_idx"),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(fields=["target_model", "target_id"], name="admin_audit_target_idx"),
        ),
    ]
