# Generated by SafeBooks on 2026-06-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safebooks", "0027_admin_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookkeeperDeactivationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=12)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "bookkeeper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deactivation_requests",
                        to="safebooks.bookkeeperaccount",
                    ),
                ),
                (
                    "reviewed_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deactivation_requests",
                        to="safebooks.adminaccount",
                    ),
                ),
            ],
            options={
                "db_table": "bookkeeper_deactivation_requests",
                "ordering": ["-requested_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="bookkeeperdeactivationrequest",
            index=models.Index(fields=["status", "-requested_at"], name="bk_deact_status_idx"),
        ),
        migrations.AddIndex(
            model_name="bookkeeperdeactivationrequest",
            index=models.Index(fields=["bookkeeper", "status"], name="bk_deact_account_idx"),
        ),
    ]
