# Generated by Django 6.0.4 on 2026-07-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safebooks', '0030_bookkeeper_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='two_factor_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='two_factor_recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminaccount',
            name='two_factor_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
